services:
  app:
    container_name: "minerva-backend"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres
    container_name: "minerva-db"
    restart: always
    shm_size: 128mb
    networks:
      - network
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: minerva-visualizer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=${DATABASE_NAME}
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db_data:
